### ISSUE TITLE
TwoPaneLayoutNav can find route for pane1 but not for pane2

### ISSUE THREAD

**Issue by tscholze** [microsoft/surface-duo-compose-sdk#56]
Hi team, 
long time no see but here I'm with another problem which is properly caused by not understanding the API.

I use the version:
```
implementation("com.microsoft.device.dualscreen:twopanelayout:1.0.1-alpha06")
```

**My code**
Based on the [tutorial](https://learn.microsoft.com/en-us/dual-screen/android/jetpack/compose/two-pane-layout), I tried to get my TwoPaneLayoutNav working.

```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            val navController = rememberNavController()

            TwoPaneLayoutNav(
                navController = navController,
                singlePaneStartDestination = "regions",
                pane1StartDestination = "regions",
                pane2StartDestination = "regions"
            ) {
                composable("regions") {
                    RegionsScreen(
                        navigateToRegion = { id -> navController.navigate("regions/${id}")}
                    )
                }
                composable("regions/{id}") { backStackEntry ->
                    val id = backStackEntry.arguments?.getString("id")
                    RegionScreen(regionId = id ?: "A")
                }
            }
        }
    }
}
``` 

**The problem* *
But as soon as I span the app across both screens, the app crashes with the following error:
```
java.lang.IllegalArgumentException: Invalid route regions, not present in list of routes []
```
I tried not just `regions` but `regions/a`, too. Both does not work. If I introduce another path like "test" is also does not work. In single screen mode, everything works as expected.

Thanks for your help!

**Comment by Papes96** [comment]
I had the same error, make sure you are importing `composable` from: 
`import com.microsoft.device.dualscreen.twopanelayout.twopanelayoutnav.composable` 
and not from: 
`import androidx.navigation.compose.composable`

**Comment by khalp** [comment]
Hi @tscholze, thanks for continuing to use our SDK and provide feedback 😄 

And thank you @Papes96 for the tip, yes you definitely want to make sure you're importing the correct `composable` definition so all routes are added to the `twoPaneBackStack`. I would also recommend that you call `navigateTo` instead of `navigate` in your `navigateToRegion` function so it will work in both single and dual screen mode!

Tobi, if that doesn't fix your problem, please let me know and provide the code for your `RegionsScreen` and `RegionScreen`! That way I can help you debug the issue some more.

**Comment by tscholze** [comment]
@Papes96 thanks, that was the fix! <3
@khalp I'm now a step further into the process to adopting the app to the surface duo. 

I may come back to the technet community with another question :)
