### ISSUE TITLE
Navigation Rail

### ISSUE THREAD

**Issue by Gaetano-Dati** [microsoft/surface-duo-compose-sdk#7]
I have a Scaffold in the MainActivity which shows a NavigatioRail or a Bottom Bar component depending on whether the app is spanned or it's a foldable Expanded device or it's a Compact/Medium display (i just used WindowsState as stated in some other Windows example projects). The NavigationRail is wrapped as a Component into a Row layout into the Scaffold and I noticed that when it's laid out Horizontally, the first pane just gets cut out at the very end whilst the second pane is laid out correctly.
One more thing: I didn't assign a weight to none of the 2 panes.
Could you please fix this? Thanks

**Comment by khalp** [comment]
Hi @Gaetano-Dati, we will look into this issue! Would you be able to provide a screenshot of the problem? Also, which device/emulator are you running your app on? Thanks in advance 😄

**Comment by Gaetano-Dati** [comment]
Good morning, thank you for replying. 
This is what I get on my Surface duo emulator when showing on double pane and Navigation Rail. 

![Screenshot_1641196901](https://user-images.githubusercontent.com/23473553/147909636-8cebb63c-3637-4930-8d7f-b897bf5bde6e.png)

And this is portrait mode, although items are split by the hinge, the card is still completely visible on it's width.

![Screenshot_1641197161](https://user-images.githubusercontent.com/23473553/147909825-6ee1ab14-e39b-4f34-a0b0-9a0a31ad6167.png)

This is the way I add my composables:

```
@ExperimentalAnimationApi
@Composable
fun ComposerExampleApp(
    windowState: WindowState
) {
    val navController = rememberAnimatedNavController()
    val scaffoldState = rememberScaffoldState()
    
    val shouldShowDualScreen = if(windowState.isPortrait()) {
        windowState.heightSizeClass == WindowSizeClass.EXPANDED
    } else windowState.widthSizeClass == WindowSizeClass.EXPANDED
    
    Scaffold(
        modifier = Modifier.fillMaxSize(),
        scaffoldState = scaffoldState,
        topBar = {
            TopBar(navController)
        },
        bottomBar = {
            if (!shouldShowDualScreen)
                BottomNavigationBar(navController)
        },
        floatingActionButton = {
            if (!shouldShowDualScreen)
                FloatingActionButton(
                    onClick = { /*TODO*/ },
                    backgroundColor = MaterialTheme.colors.primary,
                    contentColor = MaterialTheme.colors.onPrimary
                ) {
                    Icon(Icons.Filled.Email, "")
                }
        },
        isFloatingActionButtonDocked = true,
        floatingActionButtonPosition = FabPosition.End
    ) { innerPadding ->
        Row {
            if (shouldShowDualScreen)
                NavigationRailView(navController = navController)
            
            Navigation(
                navController = navController,
                innerPadding = innerPadding
            )
        }
    }
}
```

```
@ExperimentalAnimationApi
@Composable
fun Navigation(
    navController: NavHostController,
    innerPadding: PaddingValues
) {
    AnimatedNavHost(
        navController = navController,
        startDestination = Constants.HOME_GRAPH_ROUTE,
        route = Constants.ROOT_GRAPH_ROUTE,
        modifier = Modifier.padding(innerPadding).fillMaxSize()
    ) {
        homeNavGraph(navController = navController)
        musicNavGraph(navController = navController)
        booksNavGraph(navController = navController)
        profileNavGraph(navController = navController)
    }
}
```

```
@ExperimentalAnimationApi
fun NavGraphBuilder.homeNavGraph(
    navController: NavHostController
) {
    navigation(
        startDestination = NavScreen.Home.route,
        route = Constants.HOME_GRAPH_ROUTE
    ) {
        composable(
            route = NavScreen.Home.route,
            enterTransition = { fadeInTransition() },
            exitTransition = { fadeOutTransition() }
        ) {
            HomeScreen(
                onNavigate = { route -> navController.navigate(route) },
                viewModel = hiltViewModel()
            )
        }
    }
}
```

```
@ExperimentalAnimationApi
@Composable
fun HomeScreen(
    onNavigate: (route: String) -> Unit,
    viewModel: PassengersViewModel
) {
    TwoPaneLayout(
        pane1 = {
            HomeScreenRegular(
                onNavigate = { route -> onNavigate(route) },
                viewModel = viewModel,
                modifier = Modifier.weight(1F)
            )
        },
        pane2 = {
            DetailScreen(
                onNavigate = { route -> onNavigate(route) },
                viewModel = viewModel,
                modifier = Modifier.weight(1F)
            )
        },
        paneMode = TwoPaneMode.HorizontalSingle
    )
}
```
Please let me know if I was mistaken.
Also: I'd like to ask if there's a better way to implement the TwoPaneLayout using navigation.

Thanks in advance

**Comment by khalp** [comment]
Thanks for the information @Gaetano-Dati ! We actually recommend that you place navigation within your TwoPaneLayout, so the TwoPaneLayout is the highest-level composable in your app. That means your Scaffold, NavigationRail, and other layout components should exist within the TwoPaneLayout panes. For navigation, what you have looks great! It can be complicated to set up navigation within the TwoPaneLayout, so if you have any feature requests or suggestions for how to make it easier for you to use, please let us know. If you haven't seen it already, we also have a sample that uses simple navigation and a navigation rail with TwoPaneLayout: https://github.com/microsoft/surface-duo-compose-samples/tree/main/NavigationRail

**Comment by Gaetano-Dati** [comment]
Hi, I already had a look at the project about the NavigationRail. Thank you.

I do have some enhancements which I'd like to tell:

1. Insert as many panes as needed because we could also have a navigation deeper than 2 panes. What if in the DetailScreen for example we should open a WebView or something? I assume that pane1 is always the primary navigation selected either by bottom bar or nav rail or drawer

2. Then the chance to pass the NavHostController as an argument and then encourage the developer to use navigation instead of just calling navigateToPane1() or navigateToPane2() as maybe we could receive a DeepLink or need some args and so we could use the power of navigation itself instead of struggling to modify some data in the ViewModel. That way we could just have independent ViewModels for each screen

Obviously this is my own idea, I didn't take a look at the whole source code to check if it's possible to implement these features.

**Comment by khalp** [comment]
Closing this issue as discussed! Thank you for the enhancement suggestions 😄 

Note: when `Scaffold` and `TopAppBar` are placed within the panes of TwoPaneLayout, as we recommend, this can lead to a flashing in the top bar when single screen and `navigateToPane1` or `navigateToPane2` are called. This is because the navigation animation extends all the way up to the `TopAppBar`, instead of being contained within the `Scaffold` content.
